version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/services/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu

